
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/treProgetti
    driverClassName: org.postgresql.Driver
    password: 5585
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgresql
